export const COMMENT_REQUEST="GET_COMMENT_REQUEST"
export const GET_COMMENT_SUCCESS="COMMENT_SUCCESS"
export const COMMENT_FAILURE="COMMENT_FAILURE"
export const POST_COMMENT_REQUEST="POST_COMMENT_REQUEST"